// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations.ApplicationSQLiteDb
{
    [DbContext(typeof(ApplicationSQLiteDbContext))]
    [Migration("20230802224913_BlockNote")]
    partial class BlockNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BlazorApp1.CarModels.Blank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("String")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Item 1",
                            String = "This is item 1 data"
                        });
                });

            modelBuilder.Entity("BlazorApp1.CarModels.BlockNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlockNotes");
                });

            modelBuilder.Entity("BlazorApp1.CarModels.ExcelDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExcelDataRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = "ExampleData",
                            DataHash = "ExampleDataHash",
                            LastModified = new DateTime(2023, 8, 2, 17, 49, 13, 258, DateTimeKind.Local).AddTicks(5482),
                            UploadDate = new DateTime(2023, 8, 2, 17, 49, 13, 258, DateTimeKind.Local).AddTicks(5427)
                        });
                });

            modelBuilder.Entity("BlazorApp1.CarModels.ExcelDataRecordChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcelDataRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExcelDataRecordId");

                    b.ToTable("ExcelDataRecordChanges");
                });

            modelBuilder.Entity("BlazorApp1.CarModels.ExcelDataRecordChange", b =>
                {
                    b.HasOne("BlazorApp1.CarModels.ExcelDataRecord", "ExcelDataRecord")
                        .WithMany("Changes")
                        .HasForeignKey("ExcelDataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExcelDataRecord");
                });

            modelBuilder.Entity("BlazorApp1.CarModels.ExcelDataRecord", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
